allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@payloadcms/db-postgres@3.85.2'
  - '@payloadcms/drizzle@3.85.2'
  - '@payloadcms/graphql@3.85.2'
  - '@payloadcms/next@3.85.2'
  - '@payloadcms/richtext-lexical@3.85.2'
  - '@payloadcms/translations@3.85.2'
  - '@payloadcms/ui@3.85.2'
  - payload@3.85.2
